"""Rebuild assets/stylist-cards/ from the Canva exports, as one PDF per person.

Run from the dashboard root after re-exporting a deck:

    python scripts/split-stylist-cards.py

or, when only a single card has been redrawn (see SINGLE-CARD UPDATES below):

    python scripts/split-stylist-cards.py --updates-only

Kate, 2026-08-13: it has to be PDF, not an image, so the words on the card stay
selectable. The Canva exports keep their text as text, but each is one very large
file holding a whole deck, so this splits them into one single-page PDF per person.
Single-page matters twice over: iOS Safari only renders the first page of an inline
PDF, and a one-page file has nothing to scroll, so the mouse wheel keeps scrolling
the dashboard instead of being trapped by the viewer.

The weight is all in the photos, embedded for print. Capping them at 600px wide and
re-encoding as JPEG takes a page from ~3.3MB to well under 1MB and leaves the text
untouched (they still render 5x oversampled at the size the dashboard shows them).
The re-encode matters as much as the resize: Canva stores some photos as Flate PNG,
where a 576x768 costs 444KB against 31KB for the same picture as JPEG.

TRANSPARENCY. The 2026-09 decks cut the portrait out of its background, so the big
photo on each card now arrives as a 1807x2711 image with an alpha channel - and the
old rule here skipped anything with alpha, on the grounds that the only such image
was a 90x90 Instagram glyph. Left alone, one of those is most of a 4MB card. They
cannot simply be re-encoded either: PIL writes an RGBA image into a PDF as
JPEG 2000, and the pdf.js we vendor is built without an OpenJPEG decoder, so the
card would render with a hole where the stylist is. So an oversized alpha photo is
split the way a PDF normally carries one - the colour as JPEG, the alpha as a
separate DeviceGray /SMask - which is 592KB a page and renders everywhere.

An image that is already JPEG and already within the cap is left untouched, so a
deck that has been through --trim costs the split nothing and loses nothing.

THE DECKS. There are two, and the beauty team is the reason (2026-09-03):

    _source/FINAL STYLIST CARD.pdf       hair, 40 pages, 33 of them cards
    _source/FINAL BEAUTICIAN CARD.pdf    beauty, 17 pages, 11 of them cards

Both are Canva "pro" PDF exports that have been through --trim (below) before being
committed, so what is in _source is the artwork with its photos already capped at
600px. The untrimmed hair export is 439MB, and none of that weight can reach a card:
this script caps at 600px anyway. Canva holds the true masters - designs
DAHNlNvICSU (hair) and DAHTlGqLtmk (beauty) - so nothing is lost that a re-export
could not bring back at full resolution.

WHICH PAGE IS WHOSE comes from a small map committed beside each deck,
"<deck>.pages.txt". It used to come from a sibling .zip of per-page PNGs, which
worked but cost 48MB in the repo to answer a question a 33-line text file answers.
The map is generated by matching each rendered page against Kate's own named PNG
export (--remap), never typed, and every page is asserted against its own text
before a file is written under someone's name.
"""
import os
import re
import sys
import zlib

from PIL import Image
from pypdf import PdfReader, PdfWriter
from pypdf.generic import EncodedStreamObject, NameObject, NumberObject

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCE = os.path.join(ROOT, "_source")
DECKS = ["FINAL STYLIST CARD", "FINAL BEAUTICIAN CARD"]
UPDATES = os.path.join(SOURCE, "card-updates")
OUT = os.path.join(ROOT, "assets", "stylist-cards")
MAX_PHOTO_W, QUALITY = 600, 80

os.makedirs(OUT, exist_ok=True)

written, warnings = [], []


def letters(text):
    return re.sub(r"[^A-Z]", "", (text or "").upper())


def read_map(deck):
    """{page index (0-based) -> STAFF_PROFILES key} from _source/<deck>.pages.txt."""
    pages = {}
    with open(os.path.join(SOURCE, deck + ".pages.txt"), encoding="utf-8") as fh:
        for line in fh:
            line = line.split("#", 1)[0].strip()
            if not line:
                continue
            number, name = line.split(None, 1)
            pages[int(number) - 1] = name.strip()
    return pages


def is_jpeg(image):
    filters = image.indirect_reference.get_object().get("/Filter")
    return "/DCTDecode" in ([filters] if isinstance(filters, str) else list(filters or []))


def resized(img):
    height = round(img.height * MAX_PHOTO_W / img.width)
    return img.resize((MAX_PHOTO_W, height), Image.LANCZOS)


def cap(writer, image, quality):
    """One photo down to MAX_PHOTO_W and into the cheapest encoding that fits it."""
    img = image.image
    transparent = img.mode in ("RGBA", "LA", "PA") or "transparency" in img.info

    if img.width <= MAX_PHOTO_W and (is_jpeg(image) or transparent):
        # Already small, and either already JPEG or something whose transparency is
        # the point (the 90x90 Instagram glyph). Re-encoding it would only cost.
        return

    if not transparent:
        image.replace(resized(img) if img.width > MAX_PHOTO_W else img, quality=quality)
        return

    img = resized(img.convert("RGBA"))
    alpha = img.getchannel("A")
    image.replace(img.convert("RGB"), quality=quality)

    # EncodedStreamObject, not StreamObject: a plain stream hands its bytes back
    # undecoded, so a page that uses the same photo twice (Emma's does) fails to
    # read back the mask it was just given, in memory, before the file is written.
    mask = EncodedStreamObject()
    mask._data = zlib.compress(alpha.tobytes(), 9)
    mask[NameObject("/Type")] = NameObject("/XObject")
    mask[NameObject("/Subtype")] = NameObject("/Image")
    mask[NameObject("/ColorSpace")] = NameObject("/DeviceGray")
    mask[NameObject("/Filter")] = NameObject("/FlateDecode")
    mask[NameObject("/BitsPerComponent")] = NumberObject(8)
    mask[NameObject("/Width")] = NumberObject(alpha.width)
    mask[NameObject("/Height")] = NumberObject(alpha.height)
    image.indirect_reference.get_object()[NameObject("/SMask")] = writer._add_object(mask)


def squeeze(page, name, source):
    """One page as its own single-page PDF, photos capped and re-encoded.

    `name` is only used to confirm the page really is hers before a file is written
    under her name - a mis-ordered export would otherwise put one person's card
    behind another's face, which is the one failure here nobody would spot.
    """
    if name and letters(name) not in letters(page.extract_text()):
        warnings.append(f"{name}: not found in the text of {source}")

    writer = PdfWriter()
    writer.add_page(page)
    for image in writer.pages[0].images:
        cap(writer, image, QUALITY)
    return writer


def emit(name, writer):
    # Lower-cased key, spaces and all: dashboard.js asks for
    # assets/stylist-cards/<key lower-cased>.pdf, so HAZEL MAE is "hazel mae.pdf".
    path = os.path.join(OUT, name.lower() + ".pdf")
    with open(path, "wb") as fh:
        writer.write(fh)
    written.append((name.lower(), os.path.getsize(path)))


def split_decks():
    for deck in DECKS:
        reader = PdfReader(os.path.join(SOURCE, deck + ".pdf"))
        for index, name in sorted(read_map(deck).items()):
            emit(name, squeeze(reader.pages[index], name, f"{deck} page {index + 1}"))


# -- SINGLE-CARD UPDATES ------------------------------
# Kate, 2026-08-14: Katie's card was redrawn on its own - "Precision cutting" added
# to SPECIALISES IN - and arrived as one A3 PDF rather than a new deck.
#
# So any single-page PDF dropped in _source/card-updates/, named "KATIE - SENIOR
# STYLIST.pdf" or just "KATIE.pdf", is applied AFTER the deck split and overwrites
# that person's card. The ordering is the whole point: the decks are still the bulk
# source, but one of them may now be the OLDER one, and without this pass the next
# full re-export would quietly revert every card that had been updated since.
#
# It goes through the same photo squeeze as the decks - Katie's arrived at 4.2MB
# against ~800KB for the card it replaced, all of it photo weight.
def apply_updates():
    if not os.path.isdir(UPDATES):
        return
    for entry in sorted(os.listdir(UPDATES)):
        if not entry.lower().endswith(".pdf"):
            continue
        name = re.split(r"\s*-\s*", os.path.splitext(entry)[0])[0].strip()
        reader = PdfReader(os.path.join(UPDATES, entry))
        if len(reader.pages) != 1:
            warnings.append(f"{name}: {entry} has {len(reader.pages)} pages, expected 1")
            continue
        emit(name, squeeze(reader.pages[0], name, entry))


# -- PREPARING A NEW EXPORT (--trim) ------------------
# Canva's "pro" PDF export embeds the photos at print resolution: 1815px wide for a
# picture the card prints 200pt across. That is 439MB for the hair deck, none of
# which can reach a card, and GitHub's hard per-file limit is 100MB. So an export is
# put through the same cap as the split before it is committed to _source. Doing it
# here rather than only per-card is what keeps the repo honest: _source stays the
# thing every card was generated from, and it is a file a clone can actually hold.
#
#     python scripts/split-stylist-cards.py --trim <downloaded export.pdf> \
#         "_source/FINAL STYLIST CARD.pdf"
def trim(src, dst):
    reader, writer = PdfReader(src), PdfWriter()
    for page in reader.pages:
        writer.add_page(page)
    for page in writer.pages:
        for image in page.images:
            cap(writer, image, QUALITY)
    with open(dst, "wb") as fh:
        writer.write(fh)
    print(f"{os.path.basename(dst)}  {os.path.getsize(src) / 1048576:.0f}MB -> "
          f"{os.path.getsize(dst) / 1048576:.0f}MB")


# -- REBUILDING A PAGE MAP (--remap) ------------------
# Kate exports the deck as per-page PNGs too, named for the person ("HELEN -
# BLOW-DRY SPECIALIST.png"). Those names are the only authority on whose card is
# whose - the cards themselves do not all carry the name as text, Kate's is drawn -
# but a folder listing is alphabetical, not page order, so the two have to be
# matched by picture.
#
# Each page is rendered small and grey, normalised, and scored against every PNG.
# The scoring is deliberately dumb, because the answer has to be checkable: the deck
# is one template with different faces, so the runner-up is always close, and what
# makes the result trustworthy is that the assignment comes out a clean bijection
# AND that Canva's own untitled pages ("15.png") land on page 15.
#
#     python scripts/split-stylist-cards.py --remap "FINAL STYLIST CARD" <png dir>
#
# It prints the map; it does not write it. Paste it into _source/<deck>.pages.txt
# with the roles dropped and the names replaced by their STAFF_PROFILES keys.
def remap(deck, png_dir):
    import numpy as np
    import pymupdf

    def thumb(im):
        im = im.convert("L").resize((64, 90), Image.LANCZOS)
        a = np.asarray(im, dtype=np.float32)
        return (a - a.mean()) / (a.std() + 1e-6)

    doc = pymupdf.open(os.path.join(SOURCE, deck + ".pdf"))
    pages = []
    for page in doc:
        pm = page.get_pixmap(matrix=pymupdf.Matrix(0.12, 0.12), colorspace=pymupdf.csGRAY)
        pages.append(thumb(Image.frombytes("L", (pm.width, pm.height), pm.samples)))

    rows, taken = [], {}
    for entry in sorted(f for f in os.listdir(png_dir) if f.lower().endswith(".png")):
        ref = thumb(Image.open(os.path.join(png_dir, entry)))
        scores = [float(np.mean((p - ref) ** 2)) for p in pages]
        best = min(range(len(scores)), key=lambda i: scores[i])
        rows.append((best + 1, entry))
        taken.setdefault(best + 1, []).append(entry)

    for page, entry in sorted(rows):
        clash = "  <-- COLLISION" if len(taken[page]) > 1 else ""
        print(f"{page}\t{os.path.splitext(entry)[0]}{clash}")
    unmatched = [i + 1 for i in range(len(pages)) if (i + 1) not in taken]
    if unmatched:
        print("pages nothing matched:", unmatched)


if "--trim" in sys.argv:
    trim(sys.argv[sys.argv.index("--trim") + 1], sys.argv[sys.argv.index("--trim") + 2])
elif "--remap" in sys.argv:
    remap(sys.argv[sys.argv.index("--remap") + 1], sys.argv[sys.argv.index("--remap") + 2])
else:
    if "--updates-only" not in sys.argv:
        split_decks()
    apply_updates()

    for slug, size in sorted(written):
        print(f"{slug:12s} {round(size / 1024):4d} KB")
    print(f"\n{len(written)} card{'' if len(written) == 1 else 's'} written, "
          f"{sum(s for _, s in written) / 1048576:.1f} MB total")
    for w in warnings:
        print(f"WARNING  {w}")
